language: node_js
node_js:
- 0.10
install: npm install
script: grunt build
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "develop" ] && grunt build release || false'
branches:
  except:
  - master
env:
  global:
    - secure: TuMw+dzHvrql1JcC8Cp0PkNtTXbZxb77vSLJ9CpZY2D5QYnJgR2eFPvOz5fjLhwtJtW497Qc9ntmHztef1vxFxpu1hpl4M6LcwPNWbT3XbVZnVKwmVsTGGEdHiMT8Dy/0Ro9vaeLgEHHa2udBueVwIlNiNTkhtJGgxkk2+Aa8sg=
    - GIT_USER=Adrian Haasler García
    - GIT_EMAIL=dev@adrianhaasler.com
