language: node_js
node_js:
- 0.1
before_install:
- git config --global user.name "$GIT_USER"
- git config --global user.email $GIT_EMAIL
- export PATH=$PATH:`pwd`/node_modules/.bin
- export COLOS_VERSION=$(node -e "console.log(require('./package.json').version);")
install: npm install
script: npm test
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "develop" ] &&
  gulp deploy || false'
- tar -zcvf dist/hexo-theme-colos-$COLOS_VERSION.tar.gz -C dist theme --transform
  "s/theme/hexo-theme-colos-$COLOS_VERSION/"
branches:
  except:
  - master
env:
  global:
  - secure: TuMw+dzHvrql1JcC8Cp0PkNtTXbZxb77vSLJ9CpZY2D5QYnJgR2eFPvOz5fjLhwtJtW497Qc9ntmHztef1vxFxpu1hpl4M6LcwPNWbT3XbVZnVKwmVsTGGEdHiMT8Dy/0Ro9vaeLgEHHa2udBueVwIlNiNTkhtJGgxkk2+Aa8sg=
  - GIT_USER='Adrian Haasler García'
  - GIT_EMAIL=dev@adrianhaasler.com
  - GIT_REPO=github.com/ahaasler/hexo-theme-colos.git
deploy:
  provider: releases
  api_key:
    secure: gFv8SRi2TpqUSExhOJ163iV7uZ90XGMtn+wZqkHgC8HtrfJLmmyCOsqq44MoKmthOnsP1HxUNCq/GvXDu/cev6NTQW2HVQPqoPq8vos0yZ0Em0G0HbNsXstzhhylufIW2Vn2bHoM5LRXTSSfgsXmP8nDj+UuKhzlSXjme0p4CPg=
  file_glob: true
  file: dist/hexo-theme-colos-*.tar.gz
  on:
    tags: true
    repo: ahaasler/hexo-theme-colos
