# Colos theme configuration

# Menu
menu:
-
  type: link
  title: home
  path: /
-
  type: link
  title: archives
  path: archives/
-
  type: categories

# Social accounts
social:
  twitter: ahaasler
